title = "Jason Gabunilas"
# baseURL = "https://jgabunilas.github.io/JG_portfolio/"
baseURL = "https://example.com/"

languageCode = "en-us"
theme = "ananke"
# resourceDir = "../resources"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 6 # this is set low for demonstrating with dummy content. Set to a higher number
# googleAnalytics = ""
enableRobotsTXT = true
# canonifyURLs = true
# relativeURLs = true

[languages]
  [languages.en]
    title = "Jason Gabunilas"
    weight = 1
    contentDir = "content/en"
    # languageDirection = 'rtl' for Right-To-Left languages
  # [languages.fr]
  #   title = "Ananke Fr"
  #   weight = 2
  #   contentDir = "content/fr"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3
  linkedin = "https://www.linkedin.com/in/jason-gabunilas/"
  github = "https://github.com/jgabunilas"

[[module.mounts]]
source = 'static'
target = 'static'

[[module.mounts]]
source = 'images'
target = 'static/images'

# [[params.ananke_socials]]
# name = "twitter"
# url = "https://twitter.com/GoHugoIO"